### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by calgara12** [devfake/flox#157]
Hello, i'm trying to create a Dockerize this application, but I'm not getting it to work.

I found an already existing Dockerfile on Dockerhub which i modified to install php 7.4 instead of 7.0
Here is my Dockerfile:
```
FROM php:7.4-alpine

RUN apk add --update php7 php7-sqlite3 php7-json php7-phar php7-mbstring php7-openssl php7-dom php7-tokenizer php7-xml php7-pdo php7-pdo_sqlite curl git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

RUN git clone https://github.com/devfake/flox

WORKDIR flox/backend

RUN composer install

CMD tail -f /dev/null
```

Here is the docker-compose file:
```
version: '3'

services:

  db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: flox_db
    ports:
      - "3308:3306"
    networks:
      - private
    volumes:
      - data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

  app:
    image: calgara12/flox
    networks:
      - private
      - public
    ports:
      - "6030:8888"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.frontend.rule=Host:flox.mydomain.com
        - traefik.enable=true
        - traefik.port=8888
        - traefik.tags=public
        - traefik.docker.network=public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https

volumes:
  data:

networks:
  public:
    external: true
  private:
```
Once my containers are up and running I connect to my app container and type in the commands listed in your ReadMe.
```
/flox/backend # php artisan flox:init

 Enter your Database Name:
 > flox_db

 Enter your Database Username:
 > myusername

 Enter your Database Password:
 > mypass

 Enter your Database Hostname [localhost]:
 > 10.0.10.43

 Enter your Database Port [3306]:
 > 3306

/flox/backend #
```

But when i then do the db command i get an error:
```
/flox/backend # php artisan flox:db
TRYING TO MIGRATE DATABASE
Can not connect to the database. Error: could not find driver (SQL: select * from information_schema.tables where table_schema = flox_db and table_name = migrations and table_type = 'BASE TABLE')
Make sure your database credentials in .env are correct
```

Any help would be greatly appreciated :)
